### ISSUE TITLE
echo_bot example panics on wrong password

### ISSUE THREAD

**Issue by o01eg** [astro/tokio-xmpp#6]
If I enter incorrect password I get panic:

Version: 7ba1b5604f47983cba3fc283bfa61656fa652aff

```
$ RUST_BACKTRACE=1 ./target/debug/examples/echo_bot "***@bitcheese.net/RustBot" "******"
>> <stream:stream xmlns="jabber:client" to="bitcheese.net" version="1.0" xmlns:stream="http://etherx.jabber.org/streams">
>> <stream:stream to="bitcheese.net" xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0">
thread 'main' panicked at 'internal error: entered unreachable code', src/client/auth.rs:146:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/panicking.rs:411
   6: <tokio_xmpp::client::auth::ClientAuth<S> as futures::future::Future>::poll
             at src/client/auth.rs:146
   7: <futures::future::chain::Chain<A, B, C>>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:32
   8: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:32
   9: <futures::future::chain::Chain<A, B, C>>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  10: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:32
  11: <futures::future::chain::Chain<A, B, C>>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/chain.rs:26
  12: <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/and_then.rs:32
  13: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/future/mod.rs:113
  14: <tokio_xmpp::client::Client as futures::stream::Stream>::poll
             at src/client/mod.rs:126
  15: <futures::stream::split::SplitStream<S> as futures::stream::Stream>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/split.rs:27
  16: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/stream/for_each.rs:45
  17: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  18: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  19: futures::task_impl::std::set
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/std/mod.rs:78
  20: <futures::task_impl::Spawn<T>>::enter
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:396
  21: <futures::task_impl::Spawn<T>>::poll_fn_notify
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:288
  22: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.25/src/task_impl/mod.rs:326
  23: <tokio_current_thread::Entered<'a, P>>::block_on::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:479
  24: <tokio_current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:779
  25: tokio_current_thread::CurrentRunner::set_spawn
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:816
  26: <tokio_current_thread::Borrow<'a, U>>::enter::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:778
  27: <std::thread::local::LocalKey<T>>::try_with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:294
  28: <std::thread::local::LocalKey<T>>::with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:248
  29: <tokio_current_thread::Borrow<'a, U>>::enter
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:776
  30: <tokio_current_thread::Entered<'a, P>>::block_on
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.3/src/lib.rs:478
  31: tokio::runtime::current_thread::runtime::Runtime::block_on::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:187
  32: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:228
  33: tokio_executor::global::with_default::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:192
  34: <std::thread::local::LocalKey<T>>::try_with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:294
  35: <std::thread::local::LocalKey<T>>::with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:248
  36: tokio_executor::global::with_default
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.5/src/global.rs:162
  37: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:226
  38: tokio_timer::timer::handle::with_default::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:94
  39: <std::thread::local::LocalKey<T>>::try_with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:294
  40: <std::thread::local::LocalKey<T>>::with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:248
  41: tokio_timer::timer::handle::with_default
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/timer/handle.rs:81
  42: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:219
  43: tokio_timer::clock::clock::with_default::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:136
  44: <std::thread::local::LocalKey<T>>::try_with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:294
  45: <std::thread::local::LocalKey<T>>::with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:248
  46: tokio_timer::clock::clock::with_default
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.7/src/clock/clock.rs:119
  47: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:218
  48: tokio_reactor::with_default::{{closure}}
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:229
  49: <std::thread::local::LocalKey<T>>::try_with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:294
  50: <std::thread::local::LocalKey<T>>::with
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/thread/local.rs:248
  51: tokio_reactor::with_default
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.6/src/lib.rs:212
  52: tokio::runtime::current_thread::runtime::Runtime::enter
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:217
  53: tokio::runtime::current_thread::runtime::Runtime::block_on
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.11/src/runtime/current_thread/runtime.rs:185
  54: echo_bot::main
             at examples/echo_bot.rs:67
  55: std::rt::lang_start::{{closure}}
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/rt.rs:74
  56: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  57: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  58: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  59: std::rt::lang_start
             at /tmp/portage/dev-lang/rust-1.30.0/work/rustc-1.30.0-src/src/libstd/rt.rs:74
  60: main
  61: __libc_start_main
  62: _start
```

**Comment by astro** [comment]
Repository has moved. We're tracking this there now: https://gitlab.com/xmpp-rs/tokio-xmpp/issues/1
